### PR TITLE
History to the Shell component

### PR DESCRIPTION
**Pull request by francescoaru**
Dear Erich,

over the last few weeks I've been playing with PEx components and I've tried some of yours.
They are very good. Congratulations.

I added the "history" feature to the Shell component (I'm so lazy when using the console).
The behavior is very simple:
when the user hits a non-alphanumeric key the console prints the last command entered.
If the console reads another non-alphanumeric key then it prints the second command stored in the history and so on.
The history stores only 4 commands, i think they are enough.

Unfortunately the git diff does not help to see the file differences, my OS is Linux I guess the reason is the carriage return issue.

I compiled ad tested it, It should work fine. I hope you will find this feature helpful too.

Best regards,

Francesco Aru

### CODE REVIEW

**Comment by ErichStyger** [comment]
Hi Francesco,
many thanks for your contribution!

Erich

**Comment by ErichStyger** [comment]
Hi Francesco,
I have committed a few changes/fixes, I think I might make the number of history items configurable too. I see that you have configurable history line entry length (128). I think that this is a rather big default, would you be ok to set that default to say 32 characters?

Thanks again,
Erich

**Comment by francescoaru** [comment]
Hi Erich,

I've just took a look at the code.
The component was not portable because of the name of the variables and the functions.
If you give a different name to the component itself or to the referenced components, the compilation fails.
Ok, understood.

Wow, you've added the configurable items functionality and the arrow keys handler. Very cool!

Francesco

**Comment by ErichStyger** [comment]
Hi Francesco,
yes, I have changed the prefix of the functions, no problem. I had to learn this myself at the beginning too. Many thanks again for your contribution, this was on my 'wish list to do' for a very long time :-)

Erich

**Pull request merged**
